#FROM openjdk:8u151-stretch
FROM ubuntu:20.04
# Install pacakges
RUN apt update

# Install ssh
#RUN apt-get -y install openssh-client

# Confugure ssh client
#COPY id_rsa /root/.ssh/id_rsa
#RUN chmod 600 /root/.ssh/id_rsa

# Install gradle 4.2.1
#RUN mkdir /opt/gradle && \
#    wget https://downloads.gradle.org/distributions/gradle-4.2.1-bin.zip && \
#    unzip -d /opt/gradle gradle-4.2.1-bin.zip && \
#    rm gradle-4.2.1-bin.zip
#ENV PATH=$PATH:/opt/gradle/gradle-4.2.1/bin

#Install maven
RUN apt -y install maven

# Install docker 18.03
RUN apt -y install docker.io
CMD ["/bin/bash", "-l"]
