#FROM openjdk:8u151-stretch
FROM  tomcat:9-jdk11
# Install pacakges
#RUN apt update
#Install maven
#RUN apt -y install maven
# Install docker 18.03
#RUN apt -y install docker.io
RUN apt-get -y update
RUN apt install -y maven 
RUN apt install -y git 
RUN apt -y install docker.io

#CMD [ "/bin/sh" ]
