FROM  maven:3.9.6-eclipse-temurin-21-alpine
# Install pacakges
RUN apk update && apk add git
# Install docker 18.03
RUN apk add docker
#RUN apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common
#RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
#RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
#RUN apt-get update
#RUN apt-get -y install docker-ce=18.03.1~ce-0~debian
